// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyClcDC1DJ8ubMDkQTSUoAOuVl8yzZPy3p0",
    authDomain: "projectpmobprak.firebaseapp.com",
    projectId: "projectpmobprak",
    storageBucket: "projectpmobprak.appspot.com",
    messagingSenderId: "267016575564",
    appId: "1:267016575564:web:fa6668706a368c642a32e9",
    measurementId: "G-1X9ZVN30YW"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQxFwAc6VonepZmwTW5g1wGsgcpnGEXto',
    appId: '1:267016575564:android:620c06fecfe615452a32e9',
    messagingSenderId: '267016575564',
    projectId: 'projectpmobprak',
    storageBucket: 'projectpmobprak.appspot.com',
  );
}
